Controllers/ImagesController.cs
namespace WebServerMPImages.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WebServerMPImages.Services;
    using WebServerMPImages.Data;
    using WebServerMPImages.Models;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    using WebServerMPImages.Models.ViewModels;
    using System.Text.Json;
    using Microsoft.IdentityModel.Tokens;

    public class ImagesController : Controller
    {
        private readonly AppDbContext _db;

        public ImagesController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var imagesVM = new ImagesVM
            {
                ImagesGroup = _db.Products.Include(u => u.Brand).Include(u => u.Photos.OrderBy(p => p.PhotoType)).GroupBy(u => u.Brand),
                Presets = JsonSerializer.Serialize(_db.Presets.ToList())
            };
            return View(imagesVM);
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<FileResult> IndexPost([FromServices]IImageGet imageGetService, IEnumerable<string> images)
        {
            ImageParametersPreset preset = new ImageParametersPreset() 
            {
                PresetName = HttpContext.Request.Form["PresetName"],
                Width = int.Parse(HttpContext.Request.Form["Width"]),
                Height = int.Parse(HttpContext.Request.Form["Height"]),
                Padding = int.Parse(HttpContext.Request.Form["Padding"]),
                TransparentBG = !HttpContext.Request.Form["TransparentBG"].IsNullOrEmpty(),
                BGColor = HttpContext.Request.Form["BGColor"],
                NameByBarcode = !HttpContext.Request.Form["NameByBarcode"].IsNullOrEmpty(),
                Extension = (ImageExtension)int.Parse(HttpContext.Request.Form["Extension"]),            
            };

            var photosDB = _db.ProductPhoto.Include(i => i.Product).Include(i=>i.Product.Brand).Where(i => images.Contains(i.Name));

            string archiveFullName = await imageGetService.GetImages(photosDB, preset);

            return File(archiveFullName,"application/zip");
        }

        [HttpGet]
        public async Task<IActionResult> GetPresets() => Ok( await _db.Presets.ToListAsync());



    }
}

Controllers/MemoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebServerMPImages.Services;
using WebServerMPImages.Data;
using WebServerMPImages.Models;
using WebServerMPImages.Models.ViewModels;

namespace WebServerMPImages.Controllers
{
    public class MemoryController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IImageChange _imageService;
        private readonly IWebHostEnvironment _webHostEnviroment;
        private readonly string wwwrootpath;
        public MemoryController(AppDbContext db, IImageChange imageService, IWebHostEnvironment webHostEnviroment)
        {
            _db = db;
            _imageService = imageService;
            _webHostEnviroment = webHostEnviroment;
            wwwrootpath = webHostEnviroment.WebRootPath;

        }
        public IActionResult Index()
        {
            MemoryVM memoryVM = new MemoryVM();

            DirectoryInfo di = new DirectoryInfo(String.Concat(wwwrootpath,WebConst.imagePath.TrimEnd('/')));
            memoryVM.ImagesInDir = di.GetFiles().Length;
            memoryVM.ImagesSize =
                (((float)di.EnumerateFiles("*.*", SearchOption.AllDirectories).Sum(fi => fi.Length))
                /(1024 * 1024))
                .ToString("0.00")
                +" Mb";

            memoryVM.ImagesInDB = _db.ProductPhoto.Count();

            return View(memoryVM);
        }

        public IActionResult Delete()
        {
            DirectoryInfo di = new DirectoryInfo(String.Concat(wwwrootpath, WebConst.imagePath.TrimEnd('/')));
            var imagesInDir = di.GetFiles().Select(i => Path.GetFileNameWithoutExtension(i.Name));
            var imagesInDB = _db.ProductPhoto.Select(i => i.Name);

            var imagesToDelete = imagesInDir.Except(imagesInDB);

            _imageService.RemoveImages(imagesToDelete);

            return RedirectToAction(nameof(this.Index));
        }
    }
}

Controllers/ProductController.cs
namespace WebServerMPImages.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WebServerMPImages.Services;
    using WebServerMPImages.Data;
    using WebServerMPImages.Models;
    using WebServerMPImages.Models.ViewModels;
    using System.Linq;
	using Microsoft.EntityFrameworkCore;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Text.Json;
    using System.Reflection;

    public class ProductController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IImageChange _imageService;

        public ProductController(AppDbContext db, IImageChange imageService)
        {
            _db = db;
            _imageService = imageService;

        }

        public async Task<IActionResult> Index()
        {
            FullDbVM fullDbVM = new FullDbVM
            {
                Brands = _db.Brands,
                //Products = from p in _db.Products
                //           orderby p.BrandId, p.Taste, p.Volume
                //           select p
                Products = await _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).OrderBy(u => u.BrandId).ToListAsync()
            };
            return View(fullDbVM);
        }

        public IActionResult Upsert(int? Id)
        {
            Product product = Id > 0 ?
                _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).FirstOrDefault(u => u.Id == Id) ?? new Product() : 
                new Product();

            ProductVM productVM = new ProductVM
            {
                Product = product,
                BrandsDropDown = _db.Brands.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };

            return View(productVM);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(ProductVM productVM, IEnumerable<string>? allPhotos, IEnumerable<string>? photoToDelete)
        {

            //var newPhotos = new List<ProductPhoto>();

            //foreach (string photo in allPhotos.OrEmptyIfNull())
            //{
            //    newPhotos.Add(JsonSerializer.Deserialize<ProductPhoto>(photo));
            //}

            List<ProductPhoto> newPhotos = allPhotos.Select(i => JsonSerializer.Deserialize<ProductPhoto>(i)).ToList() ?? new List<ProductPhoto>();

            if (productVM.Product.Id == 0)
            {
                newPhotos.ForEach(i => i.Name = _imageService.ChangeTempName(i.Name));
                productVM.Product.Photos = newPhotos;
                _db.Products.Add(productVM.Product);
            }
            else
            {
                var currentProduct = _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType))
                    .FirstOrDefault(i => i.Id == productVM.Product.Id);

                if (currentProduct.Photos == null)
                    currentProduct.Photos = new List<ProductPhoto>();

                List<ProductPhoto> currentPhotos = currentProduct.Photos;

                //Update product properties
                Type type = currentProduct.GetType();
                PropertyInfo[] properties = type.GetProperties();
                foreach (PropertyInfo property in properties)
                {
                    property.SetValue(currentProduct, property.GetValue(productVM.Product) ?? property.GetValue(currentProduct));
                }


                foreach(var p in newPhotos.EmptyIfNull())
                {
                    if(currentPhotos.Any(i => i.Name == p.Name))
                    {
                        currentPhotos.Single(i => i.Name == p.Name).PhotoType = p.PhotoType;
                    }
                    else
                    {
                        p.Name = _imageService.ChangeTempName(p.Name);
                        currentPhotos.Add(p);
                    }
                }

                foreach(var p in photoToDelete.EmptyIfNull())
                {
                    if (currentPhotos.Any(i => i.Name == p))
                    {
                        _db.ProductPhoto.Remove(currentPhotos.Single(i => i.Name == p));
                        currentPhotos.Remove(currentPhotos.Single(i => i.Name == p));                        
                    }
                }                
            }

            await _db.SaveChangesAsync();

            if (photoToDelete!=null && photoToDelete.Count()>0)
                _imageService.RemoveImages(photoToDelete);

            return RedirectToAction(nameof(this.Index));
            
        }
                
        public IActionResult Delete(int? Id)
        {
            var product = _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).FirstOrDefault(i => i.Id == Id);

            if (product == null) return NotFound();

            var currentPhotos = product.Photos;

            foreach(var p in currentPhotos.EmptyIfNull())
            {
                _db.ProductPhoto.Remove(p);
            }
            _imageService.RemoveImages(currentPhotos.Select(i => i.Name));

            _db.Products.Remove(product);
            _db.SaveChanges();

            return RedirectToAction(nameof(this.Index));
        }

        [HttpPost]
        public async Task<IActionResult> UploadNewImages(IFormFile[] images)
        {
            if (images.Length > 0)
            {
                IEnumerable<string> newImages = await this._imageService
                    .ProcessImages(images.Select(i => new Models.Images.ImageInputModel
                    {
                        Name = Path.GetFileNameWithoutExtension(i.FileName),
                        Type = i.ContentType,
                        Content = i.OpenReadStream()
                    }));

                List<ProductPhoto> newProdPhotos = new List<ProductPhoto>();

                foreach (var image in newImages)
                {
                    newProdPhotos.Add(new ProductPhoto
                    {
                        Name = image,
                        PhotoType = PhotoType.None
                    });
                }

                return PartialView("_UploadetPhoto", newProdPhotos);
            }
            return NotFound();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebServerMPImages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebServerMPImages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebServerMPImages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="Upload">Upload Images</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="Index">Images</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Memory" asp-action="Index">Memory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebServerMPImages - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_UploadetPhoto.cshtml
@model IEnumerable<WebServerMPImages.Models.ProductPhoto>

@if(Model != null)
{    
    @foreach(var photo in Model)
    {    
        <div class="col col-3 p-1" >
            <div class="updatePhoto col bg-light border rounded-3 p-2" id="@photo.Name">
                <button type="button" class="recoverbutton position-relative top-50 start-50 translate-middle btn-info" disabled>Recover</button>
                <button type="button" class="closebutton btn-close btn-danger float-end" aria-label="Close"></button>
		        <img src="@String.Concat(WebConst.previewImagePath,photo.Name,WebConst.previewImageFormat)" class="mb-2 mx-auto d-block" height="250"/>
                
                <select asp-for="@photo.PhotoType" asp-items="Html.GetEnumSelectList<PhotoType>()" class="form-control w-auto mx-auto mb-2">
                    <option selected disabled>--Select Category--</option>
                </select>
	        </div>
        </div>
    }
}