Models/Product.cs
namespace WebServerMPImages.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string? Barcode { get; set; }
        public int BrandId { get; set; }
        public Brand Brand { get; set; }
        public string? Taste { get; set; }
        public PackType PackType { get; set; }
        public int Volume { get; set; }
        public virtual List<ProductPhoto>? Photos { get; set; }
        
    }
}

Controllers/BrandController.cs
namespace WebServerMPImages.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WebServerMPImages.Services;
    using WebServerMPImages.Data;
    using WebServerMPImages.Models.ViewModels;
    using WebServerMPImages.Models;
    using System.Linq;

    public class BrandController : Controller
    {
        private readonly AppDbContext _db;

        public BrandController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Upsert(int? Id)
        {
            Brand brand = new Brand();

            if (Id > 0)
            {
                brand = _db.Brands.Find(Id);
            }      

            return View(brand);
        }

        [HttpPost]
        public IActionResult Upsert(Brand brand)
        {
            if(brand.Id == 0)
            {
                _db.Brands.Add(brand);
            }
            else
            {
                _db.Brands.Update(brand);
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(ProductController.Index), nameof(ProductController).Replace("Controller",String.Empty));
        }

        public IActionResult Delete(int Id)
        {
            Brand brand = _db.Brands.Find(Id);
            return View(brand);
        }

        [HttpPost]
        public IActionResult Delete(Brand brand)
        {
            _db.Brands.Remove(brand);
            _db.SaveChanges();
            return RedirectToAction(nameof(ProductController.Index), nameof(ProductController).Replace("Controller",String.Empty));
        }

    }
}

Controllers/ProductController.cs
namespace WebServerMPImages.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WebServerMPImages.Services;
    using WebServerMPImages.Data;
    using WebServerMPImages.Models;
    using WebServerMPImages.Models.ViewModels;
    using System.Linq;
	using Microsoft.EntityFrameworkCore;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Text.Json;
    using System.Reflection;

    public class ProductController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IImageChange _imageService;

        public ProductController(AppDbContext db, IImageChange imageService)
        {
            _db = db;
            _imageService = imageService;

        }

        public async Task<IActionResult> Index()
        {
            FullDbVM fullDbVM = new FullDbVM
            {
                Brands = _db.Brands,
                //Products = from p in _db.Products
                //           orderby p.BrandId, p.Taste, p.Volume
                //           select p
                Products = await _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).OrderBy(u => u.BrandId).ToListAsync()
            };
            return View(fullDbVM);
        }

        public IActionResult Upsert(int? Id)
        {
            Product product = Id > 0 ?
                _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).FirstOrDefault(u => u.Id == Id) ?? new Product() : 
                new Product();

            ProductVM productVM = new ProductVM
            {
                Product = product,
                BrandsDropDown = _db.Brands.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };

            return View(productVM);
        }

        [HttpPost]
        public async Task<IActionResult> Upsert(ProductVM productVM, IEnumerable<string>? allPhotos, IEnumerable<string>? photoToDelete)
        {

            //var newPhotos = new List<ProductPhoto>();

            //foreach (string photo in allPhotos.OrEmptyIfNull())
            //{
            //    newPhotos.Add(JsonSerializer.Deserialize<ProductPhoto>(photo));
            //}

            List<ProductPhoto> newPhotos = allPhotos.Select(i => JsonSerializer.Deserialize<ProductPhoto>(i)).ToList() ?? new List<ProductPhoto>();

            if (productVM.Product.Id == 0)
            {
                newPhotos.ForEach(i => i.Name = _imageService.ChangeTempName(i.Name));
                productVM.Product.Photos = newPhotos;
                _db.Products.Add(productVM.Product);
            }
            else
            {
                var currentProduct = _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType))
                    .FirstOrDefault(i => i.Id == productVM.Product.Id);

                if (currentProduct.Photos == null)
                    currentProduct.Photos = new List<ProductPhoto>();

                List<ProductPhoto> currentPhotos = currentProduct.Photos;

                //Update product properties
                Type type = currentProduct.GetType();
                PropertyInfo[] properties = type.GetProperties();
                foreach (PropertyInfo property in properties)
                {
                    property.SetValue(currentProduct, property.GetValue(productVM.Product) ?? property.GetValue(currentProduct));
                }


                foreach(var p in newPhotos.EmptyIfNull())
                {
                    if(currentPhotos.Any(i => i.Name == p.Name))
                    {
                        currentPhotos.Single(i => i.Name == p.Name).PhotoType = p.PhotoType;
                    }
                    else
                    {
                        p.Name = _imageService.ChangeTempName(p.Name);
                        currentPhotos.Add(p);
                    }
                }

                foreach(var p in photoToDelete.EmptyIfNull())
                {
                    if (currentPhotos.Any(i => i.Name == p))
                    {
                        _db.ProductPhoto.Remove(currentPhotos.Single(i => i.Name == p));
                        currentPhotos.Remove(currentPhotos.Single(i => i.Name == p));                        
                    }
                }                
            }

            await _db.SaveChangesAsync();

            if (photoToDelete!=null && photoToDelete.Count()>0)
                _imageService.RemoveImages(photoToDelete);

            return RedirectToAction(nameof(this.Index));
            
        }
                
        public IActionResult Delete(int? Id)
        {
            var product = _db.Products.Include(u => u.Photos.OrderBy(p => p.PhotoType)).FirstOrDefault(i => i.Id == Id);

            if (product == null) return NotFound();

            var currentPhotos = product.Photos;

            foreach(var p in currentPhotos.EmptyIfNull())
            {
                _db.ProductPhoto.Remove(p);
            }
            _imageService.RemoveImages(currentPhotos.Select(i => i.Name));

            _db.Products.Remove(product);
            _db.SaveChanges();

            return RedirectToAction(nameof(this.Index));
        }

        [HttpPost]
        public async Task<IActionResult> UploadNewImages(IFormFile[] images)
        {
            if (images.Length > 0)
            {
                IEnumerable<string> newImages = await this._imageService
                    .ProcessImages(images.Select(i => new Models.Images.ImageInputModel
                    {
                        Name = Path.GetFileNameWithoutExtension(i.FileName),
                        Type = i.ContentType,
                        Content = i.OpenReadStream()
                    }));

                List<ProductPhoto> newProdPhotos = new List<ProductPhoto>();

                foreach (var image in newImages)
                {
                    newProdPhotos.Add(new ProductPhoto
                    {
                        Name = image,
                        PhotoType = PhotoType.None
                    });
                }

                return PartialView("_UploadetPhoto", newProdPhotos);
            }
            return NotFound();
        }
    }
}

Views/Product/Index.cshtml
@model WebServerMPImages.Models.ViewModels.FullDbVM

<div class="row pt-4">
	<div class="col-6">
		<h2 class="text-primary">Brand List</h2>
	</div>
	<div class="col-6 text-right">
		<a asp-controller="Brand" asp-action="Upsert" class="btn btn-primary">
			Insert new brand
		</a>
	</div>
</div>

@if (Model.Brands.Count()>0){
	<table class="table table-bordered table-striped" style="width:100%">
		<thead>
			<tr>
				<th>
					Name
				</th>
				<th>
					Type
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach(var brand in Model.Brands){
				<tr>
					<th style="width:50%">@brand.Name</th>
					<th style="width:50%">@brand.BrandType.ToString()</th>
					<td class="text-center">
						<div class="w-75 btn-group" role="group">
							<a asp-route-Id="@brand.Id" asp-controller="Brand" asp-action="Upsert" class="btn btn-primary mx-2">
								Edit
							</a>
							<a asp-route-Id="@brand.Id" asp-controller="Brand" asp-action="Delete" class="btn btn-danger mx-4">
								Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
}

<br/>

<div class="container">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Product List</h2>
		</div>
		<div class="col-6 text-right">
			<a asp-action="Upsert" class="btn btn-primary">
				Insert new Product
			</a>
		</div>
	</div>
</div>

@if (Model.Products.Count()>0){
	@foreach(var product in Model.Products){
	<div class="container">
		<div class="row justify-content-between text-primary-emphasis bg-primary bg-opacity-10 rounded-3 p-1 my-3">
			<div class="col-auto mt-2">
				<p class="productinfo py-auto"><b>@product.Brand.Name @product.Taste</b> @product.PackType @product.Volume ml</p>
			</div>
			<div class="col-auto">
				<a asp-route-Id="@product.Id" asp-controller="Product" asp-action="Upsert" class="btn btn-primary m-1">
					Edit
				</a>
				<a asp-route-Id="@product.Id" asp-controller="Product" asp-action="Delete" class="deletebutton btn btn-danger m-1">
					Delete
				</a>
			</div>
		</div>
		<div class="row ">
			@foreach(var photo in product.Photos)
			{
				<div class="col">
					<img src="@String.Concat(WebConst.previewImagePath,photo.Name,WebConst.previewImageFormat)" height="250"/>
				</div>
			}
		</div>
	</div>
	}
}

@section Scripts{
	<script src="~/js/productIndex.js"></script>
}

Views/Product/Upsert.cshtml
@model WebServerMPImages.Models.ViewModels.ProductVM

@{
	var title = "Create new product";
}

<form method="post" enctype="multipart/form-data" id="form">
	@if (Model.Product.Id != 0)
	{
		title = "Edit product";
		<input asp-for="@Model.Product.Id" hidden/>
	}
	<div class="border p-3">
		<div class="form-group row">
			<h2 class="text-info pl-3">@title</h2>
		</div>
		<div class="row">
			<div class="col-8 mb-2">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Product.BrandId"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="@Model.Product.BrandId" asp-items="@Model.BrandsDropDown" class="form-control">
                            <option selected disabled>--Select Brand--</option>
                        </select>
                        <span asp-validation-for="@Model.Product.BrandId" class="text-danger"></span>
                    </div>
                </div>

				<div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Product.Taste"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Product.Taste" class="form-control"/>
                        <span asp-validation-for="@Model.Product.Taste" class="text-danger"></span>
                    </div>
                </div>

				<div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Product.PackType"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="@Model.Product.PackType" asp-items="Html.GetEnumSelectList<PackType>()" class="form-control">
                            <option selected disabled>--Select Category--</option>
                        </select>
                        <span asp-validation-for="@Model.Product.PackType" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Product.Volume"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Product.Volume" class="form-control"/>
                        <span asp-validation-for="@Model.Product.Volume" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="@Model.Product.Barcode"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="@Model.Product.Barcode" class="form-control"/>
                        <span asp-validation-for="@Model.Product.Barcode" class="text-danger"></span>
                    </div>
                </div>
			</div>

            <div class="form-group row">
                @await Html.PartialAsync("_UploadetPhoto", @Model.Product.Photos)
            </div>

            <div id="UploadImageResult" class="form-group row"></div>  


            <div class="form-group  text-center">
		        <div class="custom-file">
			        <input type="file" id="fileUpload" class="fileUpload" multiple="multiple">
			        @*<button type="button" id="btnUpload" class="btn btn-success">Upload</button>*@
		        </div>
	        </div>
            
            <div class="form-group row">
                <div class="col-8 row">
                    <div class="col">
                        @if (Model.Product.Id != 0)
                        {
                            //update
                            <input type="submit" class="btn btn-primary w-100" value="Update"/>
                        }
                        else
                        {
                            <input type="submit" class="btn btn-primary w-100" value="Create"/>
                        }
                    </div>
                    <div class="col">
                        <a asp-controller="Product" asp-action="Index" class="btn btn-info w-100">Back</a>
                    </div>
                </div>
            </div>
		</div>

	</div>
</form>
@section Scripts{
    <script src="~/js/updateImages.js"></script>
}